Repository Curatour/frontend, pull requests merged in 2021-04, with the labels that each got.

#5 Setup/file structure
  package-lock.json
  package.json
  src/App.css
  src/App.js
  src/App.test.js
  src/components/App.css
  src/components/App.js
  src/components/calendar/Calendar.css
  src/components/calendar/Calendar.js
  src/components/common/Button.js
  src/components/common/EventCard.js
  src/components/common/NavIcon.js
  src/components/dashboard/Dashboard.css
  src/components/dashboard/Dashboard.js
  src/components/event/Event.css
  src/components/event/Event.js
  src/components/form/Form.css
  src/components/form/Form.js
  src/components/header/Header.css
  src/components/header/Header.js
  src/components/navbar/NavBar.css
  src/components/navbar/NavBar.js
  src/index.js
Labels: Calendar, FE, User, Venue

#12 Feature/navbar component
  package-lock.json
  package.json
  src/components/App.js
  src/components/common/NavIcon.js
  src/components/navbar/NavBar.css
  src/components/navbar/NavBar.js
  src/index.js
Labels: Calendar, FE, User

#13 Feature/calendar setup
  package-lock.json
  public/CTicon.png
  public/favicon.ico
  public/manifest.json
  src/assets/CuratourLogo.png
  src/components/App.css
  src/components/App.js
  src/components/form/Form.js
  src/components/header/Header.css
  src/components/header/Header.js
  src/components/navbar/NavBar.css
  src/components/navbar/NavBar.js
Labels: FE, User, enhancement

#14 Feature/setup travis ci
  .travis.yml
  cypress.json
  cypress/fixtures/example.json
  cypress/integration/home.spec.js
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  package-lock.json
  package.json
Labels: FE, testing

#16 Feature/full calendar
  cypress/integration/home.spec.js
  package-lock.json
  package.json
  src/components/calendar/Calendar.js
  src/components/calendar/CalendarWrapper.js
  src/components/calendar/event-utils.js
Labels: Calendar, FE, enhancement

#17 Feature/event form
  package-lock.json
  package.json
  public/index.html
  src/components/form/Form.css
  src/components/form/Form.js
  src/components/form/FormTime.js
  src/components/form/FormVenue.js
  src/components/navbar/NavBar.css
  src/index.css
Labels: FE, form

#18 Feature/contacts page
  package-lock.json
  src/components/App.js
  src/components/common/NavIcon.js
  src/components/contacts/ContactCard.js
  src/components/contacts/Contacts.css
  src/components/contacts/Contacts.js
  src/components/form/FormTime.js
  src/components/form/FormVenue.js
  src/components/navbar/NavBar.js
Labels: FE, User, enhancement

#20 Feature/dashboard event view
  src/components/dashboard/Dashboard.js
  src/components/dashboard/ListWrapper.js
  src/components/header/Header.js
Labels: Calendar, FE, User

#21 Feature/use context
  src/context/AppContext.js
  src/index.js
Labels: FE, documentation

#25 Add contacts component
  src/components/contacts/Contacts.js
Labels: FE, User, enhancement, form

#26 Feature/event details view
  src/components/App.js
  src/components/agenda/Agenda.css
  src/components/agenda/Agenda.js
  src/components/agenda/AgendaItem.js
  src/components/agenda/AgendaList.js
  src/components/agenda/AgendaSideBar.js
  src/components/calendar/Calendar.css
  src/components/calendar/Calendar.js
  src/components/calendar/event-utils.js
  src/components/contacts/Contacts.css
  src/components/dashboard/Dashboard.js
  src/components/event/Event.css
  src/components/event/Event.js
  src/components/navbar/NavBar.css
  src/components/navbar/NavBar.js
Labels: FE, enhancement

#28 Fix spaceing
  src/components/contacts/AddContacts.js
  src/components/contacts/Contacts.css
Labels: FE, User, bug

#27 Feature/dashboard styling
  src/components/contacts/Contacts.css
  src/components/contacts/Contacts.js
  src/components/dashboard/ContactsPreview.js
  src/components/dashboard/Dashboard.css
  src/components/dashboard/Dashboard.js
  src/components/dashboard/TourDisplay.js
Labels: FE, enhancement

#29 Feature/apollo integration
  package-lock.json
  package.json
  src/components/App.js
  src/components/calendar/Calendar.js
  src/components/calendar/CalendarWrapper.js
  src/components/calendar/event-utils.js
  src/components/dashboard/Dashboard.js
  src/context/AppContext.js
  src/context/queries.js
  src/index.js
Labels: Calendar, FE, User

#31 Feature/loading and error
  src/components/App.js
  src/components/common/Loading.js
  src/components/common/common.css
  src/components/error/NotFound.css
  src/components/error/NotFound.js
Labels: FE, enhancement

#32 Feature/mutations queries
  package-lock.json
  package.json
  src/components/App.js
  src/components/calendar/Calendar.js
  src/components/calendar/event-utils.js
  src/components/dashboard/Dashboard.js
  src/components/dashboard/TourDisplay.js
  src/components/form/Form.js
  src/components/form/FormTime.js
  src/components/form/FormVenue.js
  src/context/AppContext.js
  src/context/mutations.js
  src/context/queries.js
  src/index.js
  src/reportWebVitals.js
Labels: FE, enhancement

#34 Feature/mutations queries
  src/components/form/Form.js
  src/context/AppContext.js
  src/context/mutations.js
Labels: FE, User, enhancement

#33 Testing/setup cypress
  .travis.yml
  cypress/fixtures/contacts.json
  cypress/integration/add_contacts_spec.js
  cypress/integration/contacts_spec.js
  cypress/integration/dashboard_spec.js
  cypress/integration/header_spec.js
  cypress/integration/home.spec.js
  cypress/integration/navbar_spec.js
  cypress/integration/new_event_spec.js
  cypress/integration/not_found_spec.js
  package-lock.json
  package.json
  src/components/contacts/AddContacts.js
  src/components/header/Header.js
Labels: FE, testing

#35 Fix/styling
  cypress/integration/dashboard_spec.js
  public/index.html
  src/components/agenda/Agenda.css
  src/components/calendar/Calendar.css
  src/components/calendar/CalendarWrapper.js
  src/components/common/EventCard.js
  src/components/common/NavIcon.js
  src/components/contacts/AddContacts.js
  src/components/contacts/ContactCard.js
  src/components/contacts/Contacts.css
  src/components/contacts/Contacts.js
  src/components/dashboard/ContactsPreview.js
  src/components/dashboard/Dashboard.css
  src/components/dashboard/Dashboard.js
  src/components/dashboard/ListWrapper.js
  src/components/dashboard/TourDisplay.js
  src/components/error/NotFound.css
  src/components/event/Event.css
  src/components/event/Event.js
  src/components/form/Form.css
  src/components/header/Header.css
  src/components/navbar/NavBar.css
  src/components/navbar/NavBar.js
  src/index.css
Labels: Calendar, FE, Venue, form

#37 Fix/event detail view
  src/components/calendar/Calendar.js
  src/components/calendar/event-utils.js
  src/components/dashboard/Dashboard.js
  src/components/event/Event.js
  src/context/queries.js
Labels: Calendar, FE, Venue

#39 Styling/navbar color
  src/components/navbar/NavBar.js
Labels: FE, bug

#40 Feature/add event from calendar
  src/components/calendar/Calendar.js
  src/components/form/Form.js
Labels: Calendar, FE, User, form

#41 Feature/final mutations
  cypress/integration/add_contacts_spec.js
  cypress/integration/contacts_spec.js
  src/components/App.js
  src/components/agenda/Agenda.js
  src/components/agenda/AgendaItem.js
  src/components/agenda/AgendaSideBar.js
  src/components/calendar/Calendar.js
  src/components/calendar/event-utils.js
  src/components/contacts/AddContacts.js
  src/components/contacts/ContactCard.js
  src/components/contacts/Contacts.css
  src/components/contacts/Contacts.js
  src/components/dashboard/ContactsPreview.js
  src/components/event/Event.css
  src/components/event/Event.js
  src/components/form/Form.css
  src/components/form/Form.js
  src/context/AppContext.js
  src/context/mutations.js
  src/context/queries.js
Labels: FE, enhancement

#42 Fix/error styling
  cypress/integration/add_contacts_spec.js
  cypress/integration/contacts_spec.js
  src/components/error/NotFound.css
  src/components/error/NotFound.js
Labels: FE

#43 Feature/accessibility seo
  public/logo192.png
  public/logo512.png
  public/manifest.json
  src/components/navbar/NavBar.js
Labels: FE, bug, enhancement

#44 Feature/setup pwa
  public/icon-192x192.png
  public/icon-256x256.png
  public/icon-384x384.png
  public/icon-512x512.png
  public/index.html
  public/manifest.json
  public/sw.js
  src/components/agenda/AgendaSideBar.js
  src/components/contacts/Contacts.js
  src/components/form/Form.js
  src/index.js
  src/serviceWorkerRegistration.js
Labels: FE, enhancement

#45 Feature/sub events mutations
  src/components/App.js
  src/components/agenda/Agenda.js
  src/components/agenda/AgendaItem.js
  src/components/calendar/Calendar.js
  src/components/contacts/AddContacts.js
  src/components/contacts/Contacts.js
  src/components/dashboard/Dashboard.js
  src/components/event/Event.js
  src/components/form/Form.js
  src/context/AppContext.js
  src/context/mutations.js
  src/context/queries.js
  src/index.js
Labels: Calendar, FE, User, Venue, enhancement, form

#46 Feature/sub events mutations
  src/components/App.js
  src/components/calendar/Calendar.js
  src/components/contacts/Contacts.css
  src/components/dashboard/Dashboard.js
  src/components/form/Form.css
  src/components/form/Form.js
  src/context/AppContext.js
  src/context/queries.js
Labels: FE, enhancement

#47 Feature/testing
  cypress/fixtures/events.json
  cypress/fixtures/login.json
  cypress/fixtures/newEvent.json
  cypress/fixtures/venues.json
  cypress/integration/add_contacts_spec.js
  cypress/integration/calendar_spec.js
  cypress/integration/contacts_spec.js
  cypress/integration/dashboard_spec.js
  cypress/integration/event_details_spec.js
  cypress/integration/navbar_spec.js
  cypress/integration/new_event_spec.js
  cypress/integration/not_found_spec.js
  src/components/App.js
  src/components/error/NotFound.js
  src/components/form/Form.css
  src/components/form/Form.js
  src/components/header/navbar/NavBar.css
  src/components/header/navbar/NavBar.js
Labels: FE, testing

#56 Adjust date display on dashboard
  cypress/integration/add_contacts_spec.js
  src/components/dashboard/TourDisplay.js
Labels: FE
